### ISSUE TITLE
auto reload is always on (known)

### ISSUE THREAD

**Issue by deadmansay** [AgitationSkeleton/open_fortress#2]
you can't disable automatic reloading
![test](https://user-images.githubusercontent.com/49624449/56207490-8ae20400-6057-11e9-8b73-16a6a6463a06.png)

**Comment by zxz41** [comment]
Tested, haven't been able to recreate it. Did you remember to press OK on the Multiplayer Advanced dialogue after changing it?

**Comment by KaidemonLP** [comment]
Fixed now
