### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by SevenShanks** [AgitationSkeleton/open_fortress#40]
**Steps to Reproduce**
1. Install Source SDK Base 2013 Multiplayer.
2. Install the game using TortoiseSVN.
3. Wait for it to install.
4. Restart Steam and open the game.

**Expected Step (Did not happen during installation)**
The svn should ask for credentials.

**Expected Result**
The intro warning screen appears, after which the intro, after which the game loads, showing the title screen.

**Actual Result**
The intro warning screen does appear, after which the intro also does, but after a few second of loading, the game closes itself. Crash logs not found.

**Comment by KaydemonLP** [comment]
"The svn should ask for credentials." is not part of the instalation process anymore.
So no warning nor crash dump appeared?
What operating system are you using?

**Comment by SevenShanks** [comment]
> So no warning nor crash dump appeared?
Nothing. It just closed itself after shortly showing the loading screen, and I haven't been able to find any crash dumps.

> What operating system are you using?
Windows 10, 64x, a HP laptop, intel CORE i5. I'm not super knowledged about computer hardware and stuff so that's all I know.

**Comment by KaydemonLP** [comment]
Do you have tf2 installed and on your steam account?

**Comment by SevenShanks** [comment]
> Do you have tf2 installed and on your steam account?

I have it on my Steam account, yes. I don't have it installed since it's on my other PC. Are the files required for Open Fortress?

**Comment by KaydemonLP** [comment]
It's required to be installed, yes.
There's a error message that usually shows up saying that you need it, if you don't have it installed, not sure why its not showing up in this case.
I apologies that the requirement wasn't stated on the website, i already contacted our host to fix the issues in the tutorial.
The Discord has a more up to date installation guide since I can change that on the fly.
